### ISSUE TITLE
Using Wrapped Provider with React.createElement throws TypeError: Object [object Object] has no method 'toUpperCase'

### ISSUE THREAD

**Issue by kevzettler** [rackt/redux#633]
Following the example here
https://github.com/rackt/react-redux#react-router-013
I'm using a wrapper provider on my React Router handler

```
 <Provider store={store}>
     {() => <Handler {...ReactProps} routerState={routerState} />}
</Provider>
```

If I pass this to `React.renderToString` it renders correctly.

if I pass it to `React.createElement` it throws an error
`TypeError: Object [object Object] has no method 'toUpperCase'`

```
site-0 (err): 2015-08-27 01:32 +00:00: TypeError: Object [object Object] has no method 'toUpperCase'
site-0 (err):     at autoGenerateWrapperClass (/opt/site/node_modules/react/lib/ReactDefaultInjection.js:53:19)
site-0 (err):     at Object.getComponentClassForElement (/opt/site/node_modules/react/lib/ReactNativeComponent.js:59:49)
site-0 (err):     at validatePropTypes (/opt/site/node_modules/react/lib/ReactElementValidator.js:361:45)
site-0 (err):     at Object.ReactElementValidator.createElement (/opt/site/node_modules/react/lib/ReactElementValidator.js:408:5)
```

I'm using some 3rd party middleware that passes the wrapped handler to
`React.renderToString(React.createElement())`

I suspect this is because React is trying to get a `type` for the anonymous function ` {() => }` 

Do I have to use  an anonymous function here? can I wrap it in some other component or something?

**Comment by kevzettler** [comment]
opened in wrong repo moved to here: https://github.com/rackt/react-redux/issues/74
