### ISSUE TITLE
configureStore and Babel 6

### ISSUE THREAD

**Issue by hydrotik** [rackt/redux#997]
using:
```json
    ...
    "redux": "^3.0.4",
    ...
    "babel": "^6.0.15",
    "babel-core": "^6.0.17",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^6.0.1",
    "babel-plugin-rewire": "^0.1.22",
    "babel-plugin-syntax-jsx": "^6.0.14",
    "babel-plugin-transform-react-jsx": "^6.0.18",
    "babel-plugin-typecheck": "^2.0.0",
    "babel-polyfill": "^6.0.16",
    "babel-preset-es2015": "^6.0.15",
    "babel-runtime": "^6.0.14"
    ...
```

and the code in configureStore.es6
```javascript

import { createStore } from 'redux'
import rootReducer from '../reducers/reducers.es6';

export default function configureStore(initialState) {
  const store = createStore(rootReducer, initialState)
  return store
}
```

I get the error:
```bash
[0] ERROR in ./src/global/client/stores/configureStore.es6
[0] Module build failed: ReferenceError: /Project/src/global/client/stores/configureStore.es6: unknown node of type "NumericLiteral" with constructor "Object"
[0]     at CodeGenerator.print (/Project/node_modules/babel-generator/lib/printer.js:68:13)
[0]     at CodeGenerator.printJoin (/Project/node_modules/babel-generator/lib/printer.js:161:12)
[0]     at CodeGenerator.printList (/Project/node_modules/babel-generator/lib/printer.js:226:17)
[0]     at CodeGenerator.Sequ
[0] enceExpression (/Project/node_modules/babel-generator/lib/generators/expressions.js:107:8)
[0]     at CodeGenerator._print (/Project/node_modules/babel-generator/lib/printer.js:126:19)
[0]     at CodeGenerator.print (/Project/node_modules/babel-generator/lib/printer.js:86:10)
[0]     at CodeGenerator.CallExpression (/Project/node_modules/babel-generator/lib/generators/expressions.js:125:8)
[0]     at CodeGenerator._print (/Project/node_modules/babel-generator/lib/printer.js:126:19)
[0]     at CodeGenerator.print (/Project/node_modules/babel-generator/lib/printer.js:86:10)
[0]     at CodeGenerator.VariableDeclarator (/Project/node_modules/babel-generator/lib/generators/statements.js:281:10)
[0]     at CodeGenerator._print (/Project/node_modules/babel-generator/lib/printer.js:126:19)
[0]     at CodeGenerator.print (/Project/node_modules/babel-generator/lib/printer.js:86:10)
[0]     at CodeGenerator.printJoin (/Project/node_modules/babel-generator/lib/printer.js:161:12)
[0]     at CodeGenerator.printList (/Project/node_modules/babel-generator/lib/printer.js:226:17)
[0]     at CodeGenerator.VariableDeclaration (/Project/node_modules/babel-generator/lib/generators/statements.js:264:8)
[0]     at CodeGenerator._print (/Project/node_modules/babel-generator/lib/printer.js:126:19)
[0]  @ ./src/global/client/components/App/App.jsx 47:22-64
```

**Comment by gaearon** [comment]
Why do you think is a Redux issue?
Redux is a JavaScript library.
Using it can't break your compilation somehow.

If you use something like [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform), be aware that it [doesn't support Babel 6 yet](https://github.com/gaearon/babel-plugin-react-transform/issues/46).
